# # app-lb.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app01
# spec:
#   selector:
#     matchLabels:
#       app: app01
#   template:
#     metadata:
#       labels:
#         app: app01
#     spec:
#       containers:
#         - image: mcr.microsoft.com/dotnet/samples:aspnetapp
#           name: aspnetapp
#           ports:
#           - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app01-svc
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: app01.devopssimplelearning.com # external-dns configuration
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: app01
#   type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
  labels:
    app: loadbalancer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer-app
  template:
    metadata:
      labels:
        app: loadbalancer-app
    spec:
      containers:
        - name: loadbalancer-app
          image: leonardtia/tia:microservices
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: loadbalancer-app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app.devopseasylearning.net
spec:
  type: LoadBalancer
  selector:
    app: loadbalancer-app
  ports:
    - port: 80
      targetPort: 80

   