apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-demo-deployment
  labels:
    app: vpa-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vpa-demo
  template:
    metadata:
      labels:
        app: vpa-demo
    spec:
      containers:
      - name: vpa-demo
        image: leonardtia/tia:microservices
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "5m"       
            memory: "5Mi"            
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-demo-service
  labels:
    app: vpa-demo
spec:
  type: NodePort
  selector:
    app: vpa-demo
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 31232