apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: dev
spec:
  serviceAccountName: asume-role-s3-read-only-sa
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: 
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always