# kubectl get ClusterRoleBinding |grep eksreadonly-clusterrolebinding
# kubectl get ClusterRoleBinding eksreadonly-clusterrolebinding -oyaml

kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2022-09-08T01:19:50Z
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: HashiCorp
    operation: Update
    time: 2022-09-08T01:19:50Z
  name: eksreadonly-clusterrolebinding
  resourceVersion: "12779"
  uid: 6d389768-313f-454e-b9c0-f26b81127d2a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eksreadonly-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: eks-readonly-group
  namespace: default


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksreadonly-clusterrole
subjects:
  - kind: Group #Group or User
    name: eks-developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eksreadonly-clusterrole
  apiGroup: rbac.authorization.k8s.io